### ISSUE TITLE
Replace REST API with GRPC

### ISSUE THREAD

**Issue by cbrgm** [signalcd/signalcd#2]
We should replace the rest calls we are using now with grpc.

**Comment by metalmatze** [comment]
This issue is about the machine to machine communication, in our case about the agents talking to the API. For the web UI we should still continue with the REST based API.

**Comment by metalmatze** [comment]
I've replaced the agent to API communication with gRPC. The web UI will continue using a swagger generated REST API.
https://github.com/signalcd/signalcd/pull/19
